apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-management
  template:
    metadata:
      labels:
        app: device-management
    spec:
      containers:
        - name: device-management
          image: shdwisaac/device-management-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082