@startuml
!define RECTANGLE "rect"
!define SYSTEM "system"

title System Context Diagram - Управление отоплением

actor Пользователь as User
rectangle Монолитное_Приложение as Application {
  [Управление отоплением] as HeatingControl
  [Мониторинг температуры] as TempMonitoring
  database "PostgreSQL База данных" as DB
}

actor Датчики_Температуры as Sensors

User --> TempMonitoring : Просмотр температуры
User --> HeatingControl : Управление отоплением


Sensors --> Application : Отправка данных температуры

HeatingControl <--> DB : Хранение данных о температуре и настройках
TempMonitoring --> DB : Чтение данных

@enduml